### ISSUE TITLE
 Class 'Threaded' not found 

### ISSUE THREAD

**Issue by alokdas28** [zyzo/meteor-ddp-php#10]
Hello friends,
I install meteor-ddp-php in my server and when I try to call http://82.165.75.66/Meteor.subscribe.php or http://82.165.75.66/Meteor.call.php its showing error below
 Class 'Threaded' not found in /var/www/vhosts/smartlywallet.de/httpdocs/vendor/zyzo/meteor-ddp-php/src/zyzo/MeteorDDP/DDPSender.php on line 4

Actually when I downloaded this via composer there is no file with Class Threaded. can anyone help me.

thanks,
Alok

**Comment by enzolutions** [comment]
Hi @alokdas28 

I had the same problems as you, at the end I discover that the problem is about your PHP Version.

This library use [pthreads](https://github.com/krakjoe/pthreads) more information at http://docs.php.net/manual/en/intro.pthreads.php

If you are in Mac OSX maybe you could use brew to install a version compitble

```
$ brew install php72 --with-httpd --with-thread-safety --with-gmp
```

You need  Xcode 9.2

#Caveats

According to documentation:

The pthreads extension cannot be used in a web server environment. Threading in PHP is therefore restricted to CLI-based applications only.

pthreads (v3) can only be used with PHP 7.2+: This is due to ZTS mode being unsafe in 7.0 and 7.1.

In my case I stoped my intentions of using this library because I need to run in a web environment

**Comment by zyzo** [comment]
+1 @enzolutions. I added pthreads notice in README, then removed it https://github.com/zyzo/meteor-ddp-php/commit/ea32ac1ff0f3a94b53e490d7585f5a8c48c055bd#diff-04c6e90faac2675aa89e2176d2eec7d8L56. It is required, because in order to listen to Meteor message, you must run an async thread.

**Comment by enzolutions** [comment]
Maybe you could consider putting some mention in the readme

**Comment by zyzo** [comment]
yep, would do (again) probably
