### ISSUE TITLE
where is vendor/autoload.php?

### ISSUE THREAD

**Issue by stxh** [zyzo/meteor-ddp-php#2]
where is vendor/autoload.php?

**Comment by bfodeke** [comment]
@stxh Once you get set up with composer, you'll then have a `vendor` folder within your project

**Comment by he-mcardin** [comment]
The main DDPClient class includes the autoload.php (Line 2). But this is useless because it has to be included before the class is used.

Plus, I get an error because the path is wrong. In my case, once composer installed the package, two ../ are missing.

It works when this line is removed.

**Comment by Enelar** [comment]
This is just wrong. It shouldn't use relative path, and instead using `require vendor/autoload`.

Because i could have this structure:
`project -> git submodule -> composer require`

so i am having

```
project/
  - /vendor
  -  - autoload.php
  - /submodule
  -  - /vendor
  -  - autoload.php
  -  -  - /meteor-ddp-php
```

You never might guess where actually right autoload.php is held relative to you. Trust include path settings.

**Comment by zyzo** [comment]
Close via #6.

**Comment by zyzo** [comment]
Close via #6.
